const jobsData = [
  // Existing 1–7 jobs here...

  {
    id: 1,
    title: "Frontend Developer",
    company: "SecureWave",
    location: "Pune, India",
    category: "Job",
    workMode: "Onsite",
    employmentType: "Full-time",
    postedDate: "2 days ago",
    experienceLevel: "2+ years",
    skills: ["Security", "Python", "SIEM", "react", "javascript"],
    applyLink: "#",
    salary: "₹9-13 LPA",
    logo: "https://dummyimage.com/60x60/000/fff&text=SW"
  },
  {
    id: 2,
    title: "Frontend Developer",
    company: "SkyCloud",
    location: "Remote",
    category: "Intern",
    workMode: "Remote",
    employmentType: "Part-time",
    postedDate: "Today",
    experienceLevel: "Fresher",
    skills: ["AWS", "Azure", "DevOps", "react", "javascript"],
    applyLink: "#",
    salary: "₹10,000/month",
    logo: "https://dummyimage.com/60x60/000/fff&text=SC"
  },
  {
    id: 3,
    title: "Frontend Developer",
    company: "Insightify",
    location: "Kolkata, India",
    category: "Job",
    workMode: "Onsite",
    employmentType: "Full-time",
    postedDate: "3 days ago",
    experienceLevel: "1-2 years",
    skills: ["SQL", "Excel", "PowerBI", "react", "javascript"],
    applyLink: "#",
    salary: "₹5-8 LPA",
    logo: "https://dummyimage.com/60x60/000/fff&text=IN"
  },
  {
    id: 4,
    title: "Frontend Developer",
    company: "MobDev",
    location: "Ahmedabad, India",
    category: "Job",
    workMode: "Onsite",
    employmentType: "Full-time",
    postedDate: "4 days ago",
    experienceLevel: "1-3 years",
    skills: ["Flutter", "Dart", "Firebase", "react", "javascript"],
    applyLink: "#",
    salary: "₹6-9 LPA",
    logo: "https://dummyimage.com/60x60/000/fff&text=MD"
  },
  {
    id: 5,
    title: "Frontend Developer",
    company: "TestSphere",
    location: "Remote",
    category: "Intern",
    workMode: "Remote",
    employmentType: "Part-time",
    postedDate: "1 day ago",
    experienceLevel: "Fresher",
    skills: ["Testing", "JIRA", "Selenium", "react", "javascript"],
    applyLink: "#",
    salary: "₹7,000/month",
    logo: "https://dummyimage.com/60x60/000/fff&text=TS"
  },
  {
    id: 6,
    title: "Frontend Developer",
    company: "NeuroNet",
    location: "Bangalore, India",
    category: "Intern",
    workMode: "Onsite",
    employmentType: "Full-time",
    postedDate: "Today",
    experienceLevel: "Fresher",
    skills: ["PyTorch", "NLP", "Learning", "react", "python"],
    applyLink: "#",
    salary: "₹18,000/month",
    logo: "https://dummyimage.com/60x60/000/fff&text=NN"
  },
  {
    id: 7,
    title: "Frontend Developer",
    company: "HelpMeTech",
    location: "Nagpur, India",
    category: "Job",
    workMode: "Onsite",
    employmentType: "Full-time",
    postedDate: "6 days ago",
    experienceLevel: "0-1 years",
    skills: ["Customer", "ML", "SQL", "react"],
    applyLink: "#",
    salary: "₹4-5.5 LPA",
    logo: "https://dummyimage.com/60x60/000/fff&text=HT"
  },
  {
    id: 8,
    title: "Frontend Developer",
    company: "CreativeCore",
    location: "Delhi, India",
    category: "Job",
    workMode: "Onsite",
    employmentType: "Full-time",
    postedDate: "2 days ago",
    experienceLevel: "1-3 years",
    skills: ["Figma", "Illustrator", "Design", "react", "javascript"],
    applyLink: "#",
    salary: "₹6-8 LPA",
    logo: "https://dummyimage.com/60x60/000/fff&text=CC"
  },
  {
    id: 9,
    title: "Frontend Developer",
    company: "WebNest",
    location: "Remote",
    category: "Intern",
    workMode: "Remote",
    employmentType: "Part-time",
    postedDate: "Yesterday",
    experienceLevel: "Fresher",
    skills: ["HTML", "CSS", "JavaScript", "react"],
    applyLink: "#",
    salary: "₹6,000/month",
    logo: "https://dummyimage.com/60x60/000/fff&text=WN"
  },
  {
    id: 10,
    title: "Frontend Developer",
    company: "InnovixAI",
    location: "Mumbai, India",
    category: "Job",
    workMode: "Onsite",
    employmentType: "Full-time",
    postedDate: "1 day ago",
    experienceLevel: "3+ years",
    skills: ["AI", "ML", "Product", "react", "javascript"],
    applyLink: "#",
    salary: "₹20-25 LPA",
    logo: "https://dummyimage.com/60x60/000/fff&text=IA"
  },
  {
    id: 11,
    title: "Frontend Developer",
    company: "SecureWave",
    location: "Pune, India",
    category: "Job",
    workMode: "Onsite",
    employmentType: "Full-time",
    postedDate: "2 days ago",
    experienceLevel: "2+ years",
    skills: ["Security", "Python", "SIEM", "react", "javascript"],
    applyLink: "#",
    salary: "₹9-13 LPA",
    logo: "https://dummyimage.com/60x60/000/fff&text=SW"
  },
  {
    id: 12,
    title: "Frontend Developer",
    company: "SkyCloud",
    location: "Remote",
    category: "Intern",
    workMode: "Remote",
    employmentType: "Part-time",
    postedDate: "Today",
    experienceLevel: "Fresher",
    skills: ["AWS", "Azure", "DevOps", "react", "javascript"],
    applyLink: "#",
    salary: "₹10,000/month",
    logo: "https://dummyimage.com/60x60/000/fff&text=SC"
  },
  {
    id: 13,
    title: "Frontend Developer",
    company: "Insightify",
    location: "Kolkata, India",
    category: "Job",
    workMode: "Onsite",
    employmentType: "Full-time",
    postedDate: "3 days ago",
    experienceLevel: "1-2 years",
    skills: ["SQL", "Excel", "PowerBI", "react", "javascript"],
    applyLink: "#",
    salary: "₹5-8 LPA",
    logo: "https://dummyimage.com/60x60/000/fff&text=IN"
  },
  {
    id: 14,
    title: "Frontend Developer",
    company: "MobDev",
    location: "Ahmedabad, India",
    category: "Job",
    workMode: "Onsite",
    employmentType: "Full-time",
    postedDate: "4 days ago",
    experienceLevel: "1-3 years",
    skills: ["Flutter", "Dart", "Firebase", "react", "javascript"],
    applyLink: "#",
    salary: "₹6-9 LPA",
    logo: "https://dummyimage.com/60x60/000/fff&text=MD"
  },
  {
    id: 15,
    title: "Frontend Developer",
    company: "TestSphere",
    location: "Remote",
    category: "Intern",
    workMode: "Remote",
    employmentType: "Part-time",
    postedDate: "1 day ago",
    experienceLevel: "Fresher",
    skills: ["Testing", "JIRA", "Selenium", "react", "javascript"],
    applyLink: "#",
    salary: "₹7,000/month",
    logo: "https://dummyimage.com/60x60/000/fff&text=TS"
  },
  {
    id: 16,
    title: "Frontend Developer",
    company: "NeuroNet",
    location: "Bangalore, India",
    category: "Intern",
    workMode: "Onsite",
    employmentType: "Full-time",
    postedDate: "Today",
    experienceLevel: "Fresher",
    skills: ["PyTorch", "NLP", "Learning", "react", "python"],
    applyLink: "#",
    salary: "₹18,000/month",
    logo: "https://dummyimage.com/60x60/000/fff&text=NN"
  },
  {
    id: 17,
    title: "Frontend Developer",
    company: "HelpMeTech",
    location: "Nagpur, India",
    category: "Job",
    workMode: "Onsite",
    employmentType: "Full-time",
    postedDate: "6 days ago",
    experienceLevel: "0-1 years",
    skills: ["Customer", "ML", "SQL", "react"],
    applyLink: "#",
    salary: "₹4-5.5 LPA",
    logo: "https://dummyimage.com/60x60/000/fff&text=HT"
  },
  {
    id: 18,
    title: "Frontend Developer",
    company: "CreativeCore",
    location: "Delhi, India",
    category: "Job",
    workMode: "Onsite",
    employmentType: "Full-time",
    postedDate: "2 days ago",
    experienceLevel: "1-3 years",
    skills: ["Figma", "Illustrator", "Design", "react", "javascript"],
    applyLink: "#",
    salary: "₹6-8 LPA",
    logo: "https://dummyimage.com/60x60/000/fff&text=CC"
  },
  {
    id: 19,
    title: "Frontend Developer",
    company: "WebNest",
    location: "Remote",
    category: "Intern",
    workMode: "Remote",
    employmentType: "Part-time",
    postedDate: "Yesterday",
    experienceLevel: "Fresher",
    skills: ["HTML", "CSS", "JavaScript", "react"],
    applyLink: "#",
    salary: "₹6,000/month",
    logo: "https://dummyimage.com/60x60/000/fff&text=WN"
  },
  {
    id: 20,
    title: "Frontend Developer",
    company: "InnovixAI",
    location: "Mumbai, India",
    category: "Job",
    workMode: "Onsite",
    employmentType: "Full-time",
    postedDate: "1 day ago",
    experienceLevel: "3+ years",
    skills: ["AI", "ML", "Product", "react", "javascript"],
    applyLink: "#",
    salary: "₹20-25 LPA",
    logo: "https://dummyimage.com/60x60/000/fff&text=IA"
  },
];

export default jobsData;
