const jobsData = [
    {
      id: 1,
      title: "Frontend Developer",
      company: "TechNova",
      location: "Mumbai, India",
      category: "Job",
      workMode: "Onsite",
      employmentType: "Full-time",
      postedDate: "2 days ago",
      experienceLevel: "1-3 years",
      skills: ["React", "JavaScript", "CSS","react","javascript","node","python","aws","firebase"],
      applyLink: "#",
      salary: "₹6-9 LPA",
      logo: "https://dummyimage.com/60x60/000/fff&text=TN"
    },
    {
      id: 2,
      title: "Backend Engineer",
      company: "CodeCrafters",
      location: "Delhi, India",
      category: "Job",
      workMode: "Remote",
      employmentType: "Part-time",
      postedDate: "5 days ago",
      experienceLevel: "2+ years",
      skills: ["Node.js", "Express", "MongoDB","react","javascript","node","python","aws","firebase"],
      applyLink: "#",
      salary: "₹8-12 LPA",
      logo: "https://dummyimage.com/60x60/000/fff&text=CC"
    },
    {
      id: 3,
      title: "Full Stack Intern",
      company: "DevStudio",
      location: "Bangalore, India",
      category: "Internship",
      workMode: "Onsite",
      employmentType: "Full-time",
      postedDate: "1 day ago",
      experienceLevel: "Fresher",
      skills: ["MERN Stack", "Git", "REST APIs","react","javascript","node","python","aws","firebase"],
      applyLink: "#",
      salary: "₹15,000/month",
      logo: "https://dummyimage.com/60x60/000/fff&text=DS"
    },
    {
      id: 4,
      title: "UI/UX Intern",
      company: "DesignHut",
      location: "Remote",
      category: "Internship",
      workMode: "Remote",
      employmentType: "Part-time",
      postedDate: "3 days ago",
      experienceLevel: "Fresher",
      skills: ["Figma", "Adobe XD", "Design Systems","react","javascript","node","python","aws","firebase"],
      applyLink: "#",
      salary: "₹8,000/month",
      logo: "https://dummyimage.com/60x60/000/fff&text=DH"
    },
    {
      id: 5,
      title: "DevOps Engineer",
      company: "InfraCore",
      location: "Hyderabad, India",
      category: "Job",
      workMode: "Onsite",
      employmentType: "Part-time",
      postedDate: "6 days ago",
      experienceLevel: "3+ years",
      skills: ["Docker", "Kubernetes", "AWS","react","javascript","node","python","aws","firebase"],
      applyLink: "#",
      salary: "₹10-14 LPA",
      logo: "https://dummyimage.com/60x60/000/fff&text=IC"
    },
    {
      id: 6,
      title: "Machine Learning Intern",
      company: "DataGenius",
      location: "Chennai, India",
      category: "Internship",
      workMode: "Onsite",
      employmentType: "Part-time",
      postedDate: "2 days ago",
      experienceLevel: "Fresher",
      skills: ["Python", "TensorFlow", "Pandas","react","javascript","node","python","aws","firebase"],
      applyLink: "#",
      salary: "₹12,000/month",
      logo: "https://dummyimage.com/60x60/000/fff&text=DG"
    },
    {
      id: 7,
      title: "React Native Developer",
      company: "AppForge",
      location: "Remote",
      category: "Job",
      workMode: "Remote",
      employmentType: "Full-time",
      postedDate: "4 days ago",
      experienceLevel: "2+ years",
      skills: ["React Native", "Redux", "Firebase","react","javascript","node","python","aws","firebase"],
      applyLink: "#",
      salary: "₹7-10 LPA",
      logo: "https://dummyimage.com/60x60/000/fff&text=AF"
    }
  ];
  
  export default jobsData;
  